import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import Sidebar from "@/components/Sidebar";
import { ChatProvider } from "@/context/ChatContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Next App Class-1",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ChatProvider>
          <div className="flex h-screen overflow-hidden">
            <Sidebar />
            {/* <div className="flex flex-col flex-1 min-w-0 bg-white dark:bg-black"> */}
            {/* <Navbar /> */}
            <main className="flex-1 overflow-y-auto">
              {children}
            </main>
            {/* <Footer /> */}
            {/* </div> */}
          </div>
        </ChatProvider>
      </body>
    </html>
  );
}